### PR TITLE
fixes the regression on BucketExistsAsync

### LINKED ISSUE #1105: Regression: a commit in PR#1057 broke PR#844
A commit in PR#1057 broke PR#884 (BucketExists Async api fails to return the correct value)

The offending change is
```
if (path.ToList().Count == 1) => if (path.Count == 1)
```

We missed the fact that the purpose here was to count how many words in the list, not the number of characters in the `path` as a string.

### PR DESCRIPTION
**Pull request by ebozduman**
fixes #1105 
Regression on `BucketExistsAsync`.

### CODE REVIEW

**Review by ramondeklein — COMMENTED** [review]
There are some code changes, but the actual change that is reverted (adding back the `ToList()`) cannot fix anything.

File: Minio/RequestExtensions.cs [hunk 1]
```diff
@@ -107,10 +107,10 @@ await requestMessageBuilder.ResponseWriter(responseResult.ContentStream, cancell
                 if (request.Method == HttpMethod.Head)
                 {
                     if (responseResult.Exception?.GetType().Equals(typeof(BucketNotFoundException)) == true ||
-                        path.Length == 1)
+                        path.ToList().Count == 1)
```
[the remark this answers is not in the document]
Comment (ebozduman) [reply Minio/RequestExtensions.cs]: Done

File: Minio/RequestExtensions.cs [hunk 2]
```diff
@@ -107,10 +107,10 @@ await requestMessageBuilder.ResponseWriter(responseResult.ContentStream, cancell
...
                         responseResult.Exception = new BucketNotFoundException();
 
-                    if (path.Length > 1)
+                    if (path.ToList().Count > 1)
```
[the remark this answers is not in the document]
Comment (ebozduman) [reply Minio/RequestExtensions.cs]: Reverted back

File: Minio/RequestExtensions.cs [hunk 3]
```diff
@@ -125,7 +125,11 @@ await requestMessageBuilder.ResponseWriter(responseResult.ContentStream, cancell
                 if (request.RequestUri.ToString().Contains("lock", StringComparison.OrdinalIgnoreCase) &&
                     request.Method == HttpMethod.Get)
                     responseResult.Exception = new MissingObjectLockConfigurationException();
+                return responseResult;
```
[the remark this answers is not in the document]
Comment (ebozduman) [reply Minio/RequestExtensions.cs:131]: Yes, it is intentional as these cases are not considered to be exceptions, but rather to decide the existence of the buckets.
Those scenarios are :
- `BucketExistsAsync` api returns `true` or `false` depending on if `BucketNotFoundException` is thrown or not,
- When checking if a `lock` configuration exists or not

File: Minio/ApiEndpoints/BucketOperations.cs [hunk 4]
```diff
@@ -90,11 +90,6 @@ public async Task<bool> BucketExistsAsync(BucketExistsArgs args, CancellationTok
                     HttpStatusCode.NotFound != ice.ServerResponse.StatusCode) &&
                    ice.ServerResponse is not null;
         }
-        catch (Exception ex)
-        {
-            if (ex.GetType() == typeof(BucketNotFoundException)) return false;
-            throw;
-        }
```
[the remark this answers is not in the document]
Comment (ebozduman) [reply Minio/ApiEndpoints/BucketOperations.cs]: Done.

File: Minio/RequestExtensions.cs [hunk 5]
```diff
@@ -101,19 +100,26 @@ public static Task WrapperPutAsync(this IMinioClient minioClient, string url, St
...
+            var path = request.RequestUri.LocalPath.TrimStart('/').TrimEnd('/')
+                .Split('/', StringSplitOptions.RemoveEmptyEntries);
             if (responseResult.Response.StatusCode == HttpStatusCode.NotFound)
             {
+                if (request.RequestUri.ToString().Contains("lock", StringComparison.OrdinalIgnoreCase) &&
+                    request.Method == HttpMethod.Get)
+                {
+                    responseResult.Exception = new MissingObjectLockConfigurationException();
+                    return responseResult;
+                }
```
Comment (ramondeklein) [inline Minio/RequestExtensions.cs:112]: Just checking if the request url contains `lock` will also result in a `MissingObjectLockConfigurationException` for files that have lock in the bucket-name or key. It's much safer to actually parse the query string and check for the `object-lock` parameter:
```suggestion
                if (request.Method == HttpMethod.Get)
                {
                    var q = HttpUtility.ParseQueryString(request.RequestUri.Query);
                    if (q.Get("object-lock") != null)
                    {
                        responseResult.Exception = new MissingObjectLockConfigurationException();
                        return responseResult;
                    }
                }

```

File: Minio.Functional.Tests/FunctionalTest.cs [hunk 6]
```diff
@@ -4775,6 +4775,138 @@ internal static async Task GetObject_Test2(IMinioClient minio)
...
+                "Tests whether GetObjectAsync hits BucketNotFoundException",
+                TestStatus.FAIL, DateTime.Now - startTime, ex.Message, ex.ToString(), args: args).Log();
+            throw;
+        }
+        finally
+        {
+            if (File.Exists(tempFileName))
+                File.Delete(tempFileName);
+            await TearDown(minio, bucketName).ConfigureAwait(false);
+        }
```
Comment (ramondeklein) [inline Minio.Functional.Tests/FunctionalTest.cs:4906]: Same as previous function:
```suggestion
        var stopwatch = Stopwatch.StartNew();
        var bucketName = GetRandomName(15);
        var objectName = GetRandomObjectName(10);
        var args = new Dictionary<string, string>
            (StringComparer.Ordinal)
            {
                { "bucketName", bucketName }, 
                { "objectName", objectName },
            };
        try
        {
            // No object, no bucket, so we can hit "BucketNotFoundException" with
            var getObjectArgs = new GetObjectArgs()
                .WithBucket(bucketName)
                .WithObject(objectName)
                .WithCallbackStream(_ => throw new Exception("Should never be reached"));
            _ = await minio.GetObjectAsync(getObjectArgs).ConfigureAwait(false);

            new MintLogger("GetObjectNegBcktNotFound_Test4", getObjectSignature,
                "Tests whether GetObjectAsync hits BucketNotFoundException",
                TestStatus.FAIL, stopwatch.Elapsed, "Failed to hit BucketNotFoundException", args: args).Log();
            throw new Exception("Failed to hit BucketNotFoundException");
        }
        catch (BucketNotFoundException)
        {
            new MintLogger("GetObjectNegBcktNotFound_Test4", getObjectSignature,
                "Tests whether GetObjectAsync hits BucketNotFoundException",
                TestStatus.PASS, stopwatch.Elapsed, args: args).Log();
        }
        catch (Exception ex)
        {
            new MintLogger("GetObjectNegBcktNotFound_Test4", getObjectSignature,
                "Tests whether GetObjectAsync hits BucketNotFoundException",
                TestStatus.FAIL, stopwatch.Elapsed, ex.Message, ex.ToString(), args: args).Log();
            throw;
        }
        finally
        {
            await TearDown(minio, bucketName).ConfigureAwait(false);
        }
```

File: Minio.Functional.Tests/FunctionalTest.cs [hunk 7]
```diff
@@ -4775,6 +4775,138 @@ internal static async Task GetObject_Test2(IMinioClient minio)
...
+                "Tests whether GetObjectAsync hits ObjectNotFoundException",
+                TestStatus.FAIL, DateTime.Now - startTime, ex.Message, ex.ToString(), args: args).Log();
+            throw;
+        }
+        finally
+        {
+            if (File.Exists(tempFileName))
+                File.Delete(tempFileName);
+            await TearDown(minio, bucketName).ConfigureAwait(false);
+        }
```
Comment (ramondeklein) [inline Minio.Functional.Tests/FunctionalTest.cs:4841]: There is no need to create a stream, because there shouldn't be an object that can read. So just raise an exception if it does hit the callback-stream. You can also use a `Stopwatch` in .NET to track call durations.

This reduces code a lot:
```suggestion
        var stopwatch = Stopwatch.StartNew();
        var bucketName = GetRandomName(15);
        var objectName = GetRandomObjectName(10);
        var args = new Dictionary<string, string>
            (StringComparer.Ordinal)
            {
                { "bucketName", bucketName },
                { "objectName", objectName },
            };
        try
        {
            await Setup_Test(minio, bucketName).ConfigureAwait(false);
            // Don't Put the object, so we can hit "ObjectNotFound" exception
            var getObjectArgs = new GetObjectArgs()
                .WithBucket(bucketName)
                .WithObject(objectName)
                .WithCallbackStream(_ => throw new Exception("Should never be reached"));
            _ = await minio.GetObjectAsync(getObjectArgs).ConfigureAwait(false);

            new MintLogger("GetObjectNegObjNotFound_Test3", getObjectSignature,
                "Tests whether GetObjectAsync hits ObjectNotFoundException",
                TestStatus.FAIL, stopwatch.Elapsed, "Failed to hit ObjectNotFound exception", args: args).Log();
            throw new Exception("Failed to hit ObjectNotFound exception");
        }
        catch (ObjectNotFoundException)
        {
            new MintLogger("GetObjectNegObjNotFound_Test3", getObjectSignature,
                "Tests whether GetObjectAsync hits ObjectNotFoundException",
                TestStatus.PASS, stopwatch.Elapsed, args: args).Log();
        }
        catch (Exception ex)
        {
            new MintLogger("GetObjectNegObjNotFound_Test3", getObjectSignature,
                "Tests whether GetObjectAsync hits ObjectNotFoundException",
                TestStatus.FAIL, stopwatch.Elapsed, ex.Message, ex.ToString(), args: args).Log();
            throw;
        }
        finally
        {
            await TearDown(minio, bucketName).ConfigureAwait(false);
        }
```

**Review by ramondeklein — CHANGES_REQUESTED** [review]

File: Minio/RequestExtensions.cs (hunk 5 above)
Comment (ebozduman) [reply Minio/RequestExtensions.cs]: Done.

File: Minio.Functional.Tests/FunctionalTest.cs (hunk 6 above)
Comment (ebozduman) [reply Minio.Functional.Tests/FunctionalTest.cs]: Done.

File: Minio.Functional.Tests/FunctionalTest.cs (hunk 7 above)
Comment (ebozduman) [reply Minio.Functional.Tests/FunctionalTest.cs]: Done

**Review by ramondeklein — APPROVED** [review]
