### PR TITLE
Fix presign operations to honor request params

### LINKED ISSUE #214: "PresignedGetObjectAsync" method does not respect indicated Header parameters.
I'm trying to get a URL with temporary access with the PresignedGetObjectAsync () method to the stored object, and I intend to send the content-disposition as a parameter so that the file is downloaded with a different name from the one stored in Storage.

Upon request, a valid URL is received, which correctly downloads the file, but with the name that is in the Storage, and not with the name indicated in the Header.

The code that I am using to make the request to Mínio is:

```csharp
var _minioClient = new MinioClient(EndPoint, AccessKey, SecretKey);
var bucketName = "test";
var objectName = "folder1/testObject/abcdefgh.txt";
var expiresInt = 900;
var reqParams = new Dictionary<string, string>
{
	//{ "content-disposition", $"attachment;filename=MyDocument.txt;" },
	{ "response-content-disposition", $"inline;filename=MyDocument.txt;" },
};
return await _minioClient.PresignedGetObjectAsync(bucketName, objectName, expiresInt, reqParams).ConfigureAwait(false);
```

This returns the URL valid, but download file with name "abcdefgh.txt" instead of "MyDocument.txt".

### PR DESCRIPTION
**Pull request by poornas**
Fixes #214

### CODE REVIEW

File: Minio/V4Authenticator.cs [hunk 1]
```diff
@@ -310,7 +312,12 @@ private string GetPresignCanonicalRequest(IRestClient client, IRestRequest reque
                 path = "/" + path;
             }
             canonicalStringList.AddLast(path);
-            canonicalStringList.AddLast(requestQuery);
+            String query = requestQuery;
+            foreach (string header in headersToSign.Keys)
```
Comment (AlbertoMonteiro) [inline Minio/V4Authenticator.cs]:
```csharp
requestQuery += string.Join("", headersToSign.Select(h => $"&{h.Key}={utils.UrlEncode(h.Value)}"));
```

File: Minio/V4Authenticator.cs [hunk 2]
```diff
@@ -310,7 +312,12 @@ private string GetPresignCanonicalRequest(IRestClient client, IRestRequest reque
...
+            {
+               query = query + "&" + header + "=" + utils.UrlEncode(headersToSign[header]);
+            }
```
Comment (AlbertoMonteiro) [inline Minio/V4Authenticator.cs]: You are looping through dictionary, and then getting the value using the indexed acessor(that is a overhead), my suggestion does not get the overhead because it use the property value, from current dictionary entry.
```csharp
var query = headersToSign.Aggregate(requestQuery, (pv, cv) => $"{pv}&{h.Key}={utils.UrlEncode(h.Value)}");
```

Comment (poornas) [reply Minio/V4Authenticator.cs]: Thanks @AlbertoMonteiro, that's more concise.

**Comment by poornas** [comment]
@krisis, we have functional tests that test both presign url generation and perform a request with said URL - have updated functional tests to assert if response headers show that the request headers were honored.

**Comment by reinaldocoelho** [comment]
Do you have a release date forecast with this fix?

**Comment by poornas** [comment]
@reinaldocoelho, waiting for another PR to be merged before making  a release. Hopefully by end of day.

**Comment by reinaldocoelho** [comment]
It's wonderful.
Thank's.

**Comment by poornas** [comment]
@reinaldocoelho ,new version of .net sdk has been released with the fix.

**Comment by reinaldocoelho** [comment]
Using on my Dev branch.
Thanks 👍
